#!/bin/bash
awk -F "\"*,\"*" '{print $1}' data/kdd/kddcup.data_10_percent_processedNB/kddcup.data_10_percent_processedNB1.dump > data/kdd/kddcup.data_10_percent_processedNB/kddcup.data_10_percent_processedNBaux.dump
for i in `seq 1 30`;
do
    awk -F "\"*,\"*" '{print $5}' data/kdd/kddcup.data_10_percent_processedNB/kddcup.data_10_percent_processedNB$i.dump > data/kdd/kddcup.data_10_percent_processedNB/kddcup.data_10_percent_processedNBaux$i.dump
done
paste -d ',' data/kdd/kddcup.data_10_percent_processedNB/kddcup.data_10_percent_processedNBaux.dump data/kdd/kddcup.data_10_percent_processedNB/kddcup.data_10_percent_processedNBaux1.dump data/kdd/kddcup.data_10_percent_processedNB/kddcup.data_10_percent_processedNBaux2.dump data/kdd/kddcup.data_10_percent_processedNB/kddcup.data_10_percent_processedNBaux3.dump data/kdd/kddcup.data_10_percent_processedNB/kddcup.data_10_percent_processedNBaux4.dump data/kdd/kddcup.data_10_percent_processedNB/kddcup.data_10_percent_processedNBaux5.dump data/kdd/kddcup.data_10_percent_processedNB/kddcup.data_10_percent_processedNBaux6.dump data/kdd/kddcup.data_10_percent_processedNB/kddcup.data_10_percent_processedNBaux7.dump data/kdd/kddcup.data_10_percent_processedNB/kddcup.data_10_percent_processedNBaux8.dump data/kdd/kddcup.data_10_percent_processedNB/kddcup.data_10_percent_processedNBaux9.dump data/kdd/kddcup.data_10_percent_processedNB/kddcup.data_10_percent_processedNBaux10.dump data/kdd/kddcup.data_10_percent_processedNB/kddcup.data_10_percent_processedNBaux11.dump data/kdd/kddcup.data_10_percent_processedNB/kddcup.data_10_percent_processedNBaux12.dump data/kdd/kddcup.data_10_percent_processedNB/kddcup.data_10_percent_processedNBaux13.dump data/kdd/kddcup.data_10_percent_processedNB/kddcup.data_10_percent_processedNBaux14.dump data/kdd/kddcup.data_10_percent_processedNB/kddcup.data_10_percent_processedNBaux15.dump data/kdd/kddcup.data_10_percent_processedNB/kddcup.data_10_percent_processedNBaux16.dump data/kdd/kddcup.data_10_percent_processedNB/kddcup.data_10_percent_processedNBaux17.dump data/kdd/kddcup.data_10_percent_processedNB/kddcup.data_10_percent_processedNBaux18.dump data/kdd/kddcup.data_10_percent_processedNB/kddcup.data_10_percent_processedNBaux19.dump data/kdd/kddcup.data_10_percent_processedNB/kddcup.data_10_percent_processedNBaux20.dump data/kdd/kddcup.data_10_percent_processedNB/kddcup.data_10_percent_processedNBaux21.dump data/kdd/kddcup.data_10_percent_processedNB/kddcup.data_10_percent_processedNBaux22.dump data/kdd/kddcup.data_10_percent_processedNB/kddcup.data_10_percent_processedNBaux23.dump data/kdd/kddcup.data_10_percent_processedNB/kddcup.data_10_percent_processedNBaux24.dump data/kdd/kddcup.data_10_percent_processedNB/kddcup.data_10_percent_processedNBaux25.dump data/kdd/kddcup.data_10_percent_processedNB/kddcup.data_10_percent_processedNBaux26.dump data/kdd/kddcup.data_10_percent_processedNB/kddcup.data_10_percent_processedNBaux27.dump data/kdd/kddcup.data_10_percent_processedNB/kddcup.data_10_percent_processedNBaux28.dump data/kdd/kddcup.data_10_percent_processedNB/kddcup.data_10_percent_processedNBaux29.dump data/kdd/kddcup.data_10_percent_processedNB/kddcup.data_10_percent_processedNBaux30.dump > data/kdd/kddcup.data_10_percent_processedNB/kddcup.data_10_percent_processedNB.dump
rm data/kdd/kddcup.data_10_percent_processedNB/kddcup.data_10_percent_processedNBaux.dump
for i in `seq 1 30`;
do
    rm data/kdd/kddcup.data_10_percent_processedNB/kddcup.data_10_percent_processedNBaux$i.dump
done
