#!/bin/bash
prime=(2 3 5 7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89 97 101 103 107 109 113)
for i in `seq 1 30`;
do
    java -cp target/DDD-0.0.1-SNAPSHOT.jar moa.DoTask "EvaluatePrequential -l (meta.DDD -r ${prime[i-1]} -w 1 -l 1 -h 0.05 -e (meta.OnlineBagging -l trees.HoeffdingTree -d 0.05) -d (EarlyDriftDetectionMethod -w 0.95 -d 0.95)) -s (ArffFileStream -f data/ArtificialDataSets/plane10d/dataPlaneAddExpStyle1driftSev1Sp1Train.arff) -e (SimpleClassificationPerformanceEvaluator -r 500) -f 25 -i -1 -d data/ArtificialDataSets/plane10d/dataPlaneAddExpStyle1driftSev1Sp1Train/dataPlaneAddExpStyle1driftSev1Sp1Train$i.dump -o data/ArtificialDataSets/plane10d/dataPlaneAddExpStyle1driftSev1Sp1Train/dataPlaneAddExpStyle1driftSev1Sp1Train$i.out"
    java -cp target/DDD-0.0.1-SNAPSHOT.jar moa.DoTask "EvaluatePrequential -l (meta.DDD -r ${prime[i-1]} -w 1 -l 1 -h 0.05 -e (meta.OnlineBagging -l trees.HoeffdingTree -d 0.05) -d (EarlyDriftDetectionMethod -w 0.95 -d 0.95)) -s (ArffFileStream -f data/ArtificialDataSets/plane10d/dataPlaneAddExpStyle1driftSev1Sp2Train.arff) -e (SimpleClassificationPerformanceEvaluator -r 500) -f 25 -i -1 -d data/ArtificialDataSets/plane10d/dataPlaneAddExpStyle1driftSev1Sp2Train/dataPlaneAddExpStyle1driftSev1Sp2Train$i.dump -o data/ArtificialDataSets/plane10d/dataPlaneAddExpStyle1driftSev1Sp2Train/dataPlaneAddExpStyle1driftSev1Sp2Train$i.out"
    java -cp target/DDD-0.0.1-SNAPSHOT.jar moa.DoTask "EvaluatePrequential -l (meta.DDD -r ${prime[i-1]} -w 1 -l 1 -h 0.05 -e (meta.OnlineBagging -l trees.HoeffdingTree -d 0.05) -d (EarlyDriftDetectionMethod -w 0.95 -d 0.95)) -s (ArffFileStream -f data/ArtificialDataSets/plane10d/dataPlaneAddExpStyle1driftSev1Sp3Train.arff) -e (SimpleClassificationPerformanceEvaluator -r 500) -f 25 -i -1 -d data/ArtificialDataSets/plane10d/dataPlaneAddExpStyle1driftSev1Sp3Train/dataPlaneAddExpStyle1driftSev1Sp3Train$i.dump -o data/ArtificialDataSets/plane10d/dataPlaneAddExpStyle1driftSev1Sp3Train/dataPlaneAddExpStyle1driftSev1Sp3Train$i.out"
    java -cp target/DDD-0.0.1-SNAPSHOT.jar moa.DoTask "EvaluatePrequential -l (meta.DDD -r ${prime[i-1]} -w 1 -l 1 -h 0.05 -e (meta.OnlineBagging -l trees.HoeffdingTree -d 0.05) -d (EarlyDriftDetectionMethod -w 0.95 -d 0.95)) -s (ArffFileStream -f data/ArtificialDataSets/plane10d/dataPlaneAddExpStyle1driftSev1Test.arff) -e (SimpleClassificationPerformanceEvaluator -r 100) -f 25 -i -1 -d data/ArtificialDataSets/plane10d/dataPlaneAddExpStyle1driftSev1Test/dataPlaneAddExpStyle1driftSev1Test$i.dump -o data/ArtificialDataSets/plane10d/dataPlaneAddExpStyle1driftSev1Test/dataPlaneAddExpStyle1driftSev1Test$i.out"
    java -cp target/DDD-0.0.1-SNAPSHOT.jar moa.DoTask "EvaluatePrequential -l (meta.DDD -r ${prime[i-1]} -w 1 -l 1 -h 0.05 -e (meta.OnlineBagging -l trees.HoeffdingTree -d 0.05) -d (EarlyDriftDetectionMethod -w 0.95 -d 0.95)) -s (ArffFileStream -f data/ArtificialDataSets/plane10d/dataPlaneAddExpStyle1driftSev2Sp1Train.arff) -e (SimpleClassificationPerformanceEvaluator -r 500) -f 25 -i -1 -d data/ArtificialDataSets/plane10d/dataPlaneAddExpStyle1driftSev2Sp1Train/dataPlaneAddExpStyle1driftSev2Sp1Train$i.dump -o data/ArtificialDataSets/plane10d/dataPlaneAddExpStyle1driftSev2Sp1Train/dataPlaneAddExpStyle1driftSev2Sp1Train$i.out"
    java -cp target/DDD-0.0.1-SNAPSHOT.jar moa.DoTask "EvaluatePrequential -l (meta.DDD -r ${prime[i-1]} -w 1 -l 1 -h 0.05 -e (meta.OnlineBagging -l trees.HoeffdingTree -d 0.05) -d (EarlyDriftDetectionMethod -w 0.95 -d 0.95)) -s (ArffFileStream -f data/ArtificialDataSets/plane10d/dataPlaneAddExpStyle1driftSev2Sp2Train.arff) -e (SimpleClassificationPerformanceEvaluator -r 500) -f 25 -i -1 -d data/ArtificialDataSets/plane10d/dataPlaneAddExpStyle1driftSev2Sp2Train/dataPlaneAddExpStyle1driftSev2Sp2Train$i.dump -o data/ArtificialDataSets/plane10d/dataPlaneAddExpStyle1driftSev2Sp2Train/dataPlaneAddExpStyle1driftSev2Sp2Train$i.out"
    java -cp target/DDD-0.0.1-SNAPSHOT.jar moa.DoTask "EvaluatePrequential -l (meta.DDD -r ${prime[i-1]} -w 1 -l 1 -h 0.05 -e (meta.OnlineBagging -l trees.HoeffdingTree -d 0.05) -d (EarlyDriftDetectionMethod -w 0.95 -d 0.95)) -s (ArffFileStream -f data/ArtificialDataSets/plane10d/dataPlaneAddExpStyle1driftSev2Sp3Train.arff) -e (SimpleClassificationPerformanceEvaluator -r 500) -f 25 -i -1 -d data/ArtificialDataSets/plane10d/dataPlaneAddExpStyle1driftSev2Sp3Train/dataPlaneAddExpStyle1driftSev2Sp3Train$i.dump -o data/ArtificialDataSets/plane10d/dataPlaneAddExpStyle1driftSev2Sp3Train/dataPlaneAddExpStyle1driftSev2Sp3Train$i.out"
    java -cp target/DDD-0.0.1-SNAPSHOT.jar moa.DoTask "EvaluatePrequential -l (meta.DDD -r ${prime[i-1]} -w 1 -l 1 -h 0.05 -e (meta.OnlineBagging -l trees.HoeffdingTree -d 0.05) -d (EarlyDriftDetectionMethod -w 0.95 -d 0.95)) -s (ArffFileStream -f data/ArtificialDataSets/plane10d/dataPlaneAddExpStyle1driftSev2Test.arff) -e (SimpleClassificationPerformanceEvaluator -r 100) -f 25 -i -1 -d data/ArtificialDataSets/plane10d/dataPlaneAddExpStyle1driftSev2Test/dataPlaneAddExpStyle1driftSev2Test$i.dump -o data/ArtificialDataSets/plane10d/dataPlaneAddExpStyle1driftSev2Test/dataPlaneAddExpStyle1driftSev2Test$i.out"
    java -cp target/DDD-0.0.1-SNAPSHOT.jar moa.DoTask "EvaluatePrequential -l (meta.DDD -r ${prime[i-1]} -w 1 -l 1 -h 0.05 -e (meta.OnlineBagging -l trees.HoeffdingTree -d 0.05) -d (EarlyDriftDetectionMethod -w 0.95 -d 0.95)) -s (ArffFileStream -f data/ArtificialDataSets/plane10d/dataPlaneAddExpStyle1driftSev3Sp1Train.arff) -e (SimpleClassificationPerformanceEvaluator -r 500) -f 25 -i -1 -d data/ArtificialDataSets/plane10d/dataPlaneAddExpStyle1driftSev3Sp1Train/dataPlaneAddExpStyle1driftSev3Sp1Train$i.dump -o data/ArtificialDataSets/plane10d/dataPlaneAddExpStyle1driftSev3Sp1Train/dataPlaneAddExpStyle1driftSev3Sp1Train$i.out"
    java -cp target/DDD-0.0.1-SNAPSHOT.jar moa.DoTask "EvaluatePrequential -l (meta.DDD -r ${prime[i-1]} -w 1 -l 1 -h 0.05 -e (meta.OnlineBagging -l trees.HoeffdingTree -d 0.05) -d (EarlyDriftDetectionMethod -w 0.95 -d 0.95)) -s (ArffFileStream -f data/ArtificialDataSets/plane10d/dataPlaneAddExpStyle1driftSev3Sp2Train.arff) -e (SimpleClassificationPerformanceEvaluator -r 500) -f 25 -i -1 -d data/ArtificialDataSets/plane10d/dataPlaneAddExpStyle1driftSev3Sp2Train/dataPlaneAddExpStyle1driftSev3Sp2Train$i.dump -o data/ArtificialDataSets/plane10d/dataPlaneAddExpStyle1driftSev3Sp2Train/dataPlaneAddExpStyle1driftSev3Sp2Train$i.out"
    java -cp target/DDD-0.0.1-SNAPSHOT.jar moa.DoTask "EvaluatePrequential -l (meta.DDD -r ${prime[i-1]} -w 1 -l 1 -h 0.05 -e (meta.OnlineBagging -l trees.HoeffdingTree -d 0.05) -d (EarlyDriftDetectionMethod -w 0.95 -d 0.95)) -s (ArffFileStream -f data/ArtificialDataSets/plane10d/dataPlaneAddExpStyle1driftSev3Sp3Train.arff) -e (SimpleClassificationPerformanceEvaluator -r 500) -f 25 -i -1 -d data/ArtificialDataSets/plane10d/dataPlaneAddExpStyle1driftSev3Sp3Train/dataPlaneAddExpStyle1driftSev3Sp3Train$i.dump -o data/ArtificialDataSets/plane10d/dataPlaneAddExpStyle1driftSev3Sp3Train/dataPlaneAddExpStyle1driftSev3Sp3Train$i.out"
    java -cp target/DDD-0.0.1-SNAPSHOT.jar moa.DoTask "EvaluatePrequential -l (meta.DDD -r ${prime[i-1]} -w 1 -l 1 -h 0.05 -e (meta.OnlineBagging -l trees.HoeffdingTree -d 0.05) -d (EarlyDriftDetectionMethod -w 0.95 -d 0.95)) -s (ArffFileStream -f data/ArtificialDataSets/plane10d/dataPlaneAddExpStyle1driftSev3Test.arff) -e (SimpleClassificationPerformanceEvaluator -r 100) -f 25 -i -1 -d data/ArtificialDataSets/plane10d/dataPlaneAddExpStyle1driftSev3Test/dataPlaneAddExpStyle1driftSev3Test$i.dump -o data/ArtificialDataSets/plane10d/dataPlaneAddExpStyle1driftSev3Test/dataPlaneAddExpStyle1driftSev3Test$i.out"
done