#!/bin/bash
prime=(2 3 5 7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89 97 101 103 107 109 113)
rm data/ArtificialDataSets/sineH/dataSineHSev1Sp1Test/dataSineHSev1Sp1Test*.dump
rm data/ArtificialDataSets/sineH/dataSineHSev1Sp1Test/dataSineHSev1Sp1Test*.out
rm data/ArtificialDataSets/sineH/dataSineHSev1Sp1Train/dataSineHSev1Sp1Train*.dump
rm data/ArtificialDataSets/sineH/dataSineHSev1Sp1Train/dataSineHSev1Sp1Train*.out
rm data/ArtificialDataSets/sineH/dataSineHSev1Sp2Train/dataSineHSev1Sp2Train*.dump
rm data/ArtificialDataSets/sineH/dataSineHSev1Sp2Train/dataSineHSev1Sp2Train*.out
rm data/ArtificialDataSets/sineH/dataSineHSev1Sp3Train/dataSineHSev1Sp3Train*.dump
rm data/ArtificialDataSets/sineH/dataSineHSev1Sp3Train/dataSineHSev1Sp3Train*.out
rm data/ArtificialDataSets/sineH/dataSineHSev2Sp1Test/dataSineHSev2Sp1Test*.dump
rm data/ArtificialDataSets/sineH/dataSineHSev2Sp1Test/dataSineHSev2Sp1Test*.out
rm data/ArtificialDataSets/sineH/dataSineHSev2Sp1Train/dataSineHSev2Sp1Train*.dump
rm data/ArtificialDataSets/sineH/dataSineHSev2Sp1Train/dataSineHSev2Sp1Train*.out
rm data/ArtificialDataSets/sineH/dataSineHSev2Sp2Train/dataSineHSev2Sp2Train*.dump
rm data/ArtificialDataSets/sineH/dataSineHSev2Sp2Train/dataSineHSev2Sp2Train*.out
rm data/ArtificialDataSets/sineH/dataSineHSev2Sp3Train/dataSineHSev2Sp3Train*.dump
rm data/ArtificialDataSets/sineH/dataSineHSev2Sp3Train/dataSineHSev2Sp3Train*.out
rm data/ArtificialDataSets/sineH/dataSineHSev3Sp1Test/dataSineHSev3Sp1Test*.dump
rm data/ArtificialDataSets/sineH/dataSineHSev3Sp1Test/dataSineHSev3Sp1Test*.out
rm data/ArtificialDataSets/sineH/dataSineHSev3Sp1Train/dataSineHSev3Sp1Train*.dump
rm data/ArtificialDataSets/sineH/dataSineHSev3Sp1Train/dataSineHSev3Sp1Train*.out
rm data/ArtificialDataSets/sineH/dataSineHSev3Sp2Train/dataSineHSev3Sp2Train*.dump
rm data/ArtificialDataSets/sineH/dataSineHSev3Sp2Train/dataSineHSev3Sp2Train*.out
rm data/ArtificialDataSets/sineH/dataSineHSev3Sp3Train/dataSineHSev3Sp3Train*.dump
rm data/ArtificialDataSets/sineH/dataSineHSev3Sp3Train/dataSineHSev3Sp3Train*.out
for i in `seq 1 30`;
do
    java -cp target/DDD-0.0.1-SNAPSHOT.jar moa.DoTask "EvaluatePrequential -l (meta.DDD -r ${prime[i-1]} -w 1 -l 1 -h 0.05 -e (meta.OnlineBagging -l trees.HoeffdingTree -d 0.05) -d (EarlyDriftDetectionMethod -w 0.95 -d 0.95)) -s (ArffFileStream -f data/ArtificialDataSets/sineH/dataSineHSev1Sp1Test.arff) -e (SimpleClassificationPerformanceEvaluator -r 250) -f 10 -i -1 -d data/ArtificialDataSets/sineH/dataSineHSev1Sp1Test/dataSineHSev1Sp1Test$i.dump -o data/ArtificialDataSets/sineH/dataSineHSev1Sp1Test/dataSineHSev1Sp1Test$i.out"
    java -cp target/DDD-0.0.1-SNAPSHOT.jar moa.DoTask "EvaluatePrequential -l (meta.DDD -r ${prime[i-1]} -w 1 -l 1 -h 0.05 -e (meta.OnlineBagging -l trees.HoeffdingTree -d 0.05) -d (EarlyDriftDetectionMethod -w 0.95 -d 0.95)) -s (ArffFileStream -f data/ArtificialDataSets/sineH/dataSineHSev1Sp1Train.arff) -e (SimpleClassificationPerformanceEvaluator -r 1000) -f 10 -i -1 -d data/ArtificialDataSets/sineH/dataSineHSev1Sp1Train/dataSineHSev1Sp1Train$i.dump -o data/ArtificialDataSets/sineH/dataSineHSev1Sp1Train/dataSineHSev1Sp1Train$i.out"
    java -cp target/DDD-0.0.1-SNAPSHOT.jar moa.DoTask "EvaluatePrequential -l (meta.DDD -r ${prime[i-1]} -w 1 -l 1 -h 0.05 -e (meta.OnlineBagging -l trees.HoeffdingTree -d 0.05) -d (EarlyDriftDetectionMethod -w 0.95 -d 0.95)) -s (ArffFileStream -f data/ArtificialDataSets/sineH/dataSineHSev1Sp2Train.arff) -e (SimpleClassificationPerformanceEvaluator -r 1000) -f 10 -i -1 -d data/ArtificialDataSets/sineH/dataSineHSev1Sp2Train/dataSineHSev1Sp2Train$i.dump -o data/ArtificialDataSets/sineH/dataSineHSev1Sp2Train/dataSineHSev1Sp2Train$i.out"
    java -cp target/DDD-0.0.1-SNAPSHOT.jar moa.DoTask "EvaluatePrequential -l (meta.DDD -r ${prime[i-1]} -w 1 -l 1 -h 0.05 -e (meta.OnlineBagging -l trees.HoeffdingTree -d 0.05) -d (EarlyDriftDetectionMethod -w 0.95 -d 0.95)) -s (ArffFileStream -f data/ArtificialDataSets/sineH/dataSineHSev1Sp3Train.arff) -e (SimpleClassificationPerformanceEvaluator -r 1000) -f 10 -i -1 -d data/ArtificialDataSets/sineH/dataSineHSev1Sp3Train/dataSineHSev1Sp3Train$i.dump -o data/ArtificialDataSets/sineH/dataSineHSev1Sp3Train/dataSineHSev1Sp3Train$i.out"
    java -cp target/DDD-0.0.1-SNAPSHOT.jar moa.DoTask "EvaluatePrequential -l (meta.DDD -r ${prime[i-1]} -w 1 -l 1 -h 0.05 -e (meta.OnlineBagging -l trees.HoeffdingTree -d 0.05) -d (EarlyDriftDetectionMethod -w 0.95 -d 0.95)) -s (ArffFileStream -f data/ArtificialDataSets/sineH/dataSineHSev2Sp1Test.arff) -e (SimpleClassificationPerformanceEvaluator -r 250) -f 10 -i -1 -d data/ArtificialDataSets/sineH/dataSineHSev2Sp1Test/dataSineHSev2Sp1Test$i.dump -o data/ArtificialDataSets/sineH/dataSineHSev2Sp1Test/dataSineHSev2Sp1Test$i.out"
    java -cp target/DDD-0.0.1-SNAPSHOT.jar moa.DoTask "EvaluatePrequential -l (meta.DDD -r ${prime[i-1]} -w 1 -l 1 -h 0.05 -e (meta.OnlineBagging -l trees.HoeffdingTree -d 0.05) -d (EarlyDriftDetectionMethod -w 0.95 -d 0.95)) -s (ArffFileStream -f data/ArtificialDataSets/sineH/dataSineHSev2Sp1Train.arff) -e (SimpleClassificationPerformanceEvaluator -r 1000) -f 10 -i -1 -d data/ArtificialDataSets/sineH/dataSineHSev2Sp1Train/dataSineHSev2Sp1Train$i.dump -o data/ArtificialDataSets/sineH/dataSineHSev2Sp1Train/dataSineHSev2Sp1Train$i.out"
    java -cp target/DDD-0.0.1-SNAPSHOT.jar moa.DoTask "EvaluatePrequential -l (meta.DDD -r ${prime[i-1]} -w 1 -l 1 -h 0.05 -e (meta.OnlineBagging -l trees.HoeffdingTree -d 0.05) -d (EarlyDriftDetectionMethod -w 0.95 -d 0.95)) -s (ArffFileStream -f data/ArtificialDataSets/sineH/dataSineHSev2Sp2Train.arff) -e (SimpleClassificationPerformanceEvaluator -r 1000) -f 10 -i -1 -d data/ArtificialDataSets/sineH/dataSineHSev2Sp2Train/dataSineHSev2Sp2Train$i.dump -o data/ArtificialDataSets/sineH/dataSineHSev2Sp2Train/dataSineHSev2Sp2Train$i.out"
    java -cp target/DDD-0.0.1-SNAPSHOT.jar moa.DoTask "EvaluatePrequential -l (meta.DDD -r ${prime[i-1]} -w 1 -l 1 -h 0.05 -e (meta.OnlineBagging -l trees.HoeffdingTree -d 0.05) -d (EarlyDriftDetectionMethod -w 0.95 -d 0.95)) -s (ArffFileStream -f data/ArtificialDataSets/sineH/dataSineHSev2Sp3Train.arff) -e (SimpleClassificationPerformanceEvaluator -r 1000) -f 10 -i -1 -d data/ArtificialDataSets/sineH/dataSineHSev2Sp3Train/dataSineHSev2Sp3Train$i.dump -o data/ArtificialDataSets/sineH/dataSineHSev2Sp3Train/dataSineHSev2Sp3Train$i.out"
    java -cp target/DDD-0.0.1-SNAPSHOT.jar moa.DoTask "EvaluatePrequential -l (meta.DDD -r ${prime[i-1]} -w 1 -l 1 -h 0.05 -e (meta.OnlineBagging -l trees.HoeffdingTree -d 0.05) -d (EarlyDriftDetectionMethod -w 0.95 -d 0.95)) -s (ArffFileStream -f data/ArtificialDataSets/sineH/dataSineHSev3Sp1Test.arff) -e (SimpleClassificationPerformanceEvaluator -r 250) -f 10 -i -1 -d data/ArtificialDataSets/sineH/dataSineHSev3Sp1Test/dataSineHSev3Sp1Test$i.dump -o data/ArtificialDataSets/sineH/dataSineHSev3Sp1Test/dataSineHSev3Sp1Test$i.out"
    java -cp target/DDD-0.0.1-SNAPSHOT.jar moa.DoTask "EvaluatePrequential -l (meta.DDD -r ${prime[i-1]} -w 1 -l 1 -h 0.05 -e (meta.OnlineBagging -l trees.HoeffdingTree -d 0.05) -d (EarlyDriftDetectionMethod -w 0.95 -d 0.95)) -s (ArffFileStream -f data/ArtificialDataSets/sineH/dataSineHSev3Sp1Train.arff) -e (SimpleClassificationPerformanceEvaluator -r 1000) -f 10 -i -1 -d data/ArtificialDataSets/sineH/dataSineHSev3Sp1Train/dataSineHSev3Sp1Train$i.dump -o data/ArtificialDataSets/sineH/dataSineHSev3Sp1Train/dataSineHSev3Sp1Train$i.out"
    java -cp target/DDD-0.0.1-SNAPSHOT.jar moa.DoTask "EvaluatePrequential -l (meta.DDD -r ${prime[i-1]} -w 1 -l 1 -h 0.05 -e (meta.OnlineBagging -l trees.HoeffdingTree -d 0.05) -d (EarlyDriftDetectionMethod -w 0.95 -d 0.95)) -s (ArffFileStream -f data/ArtificialDataSets/sineH/dataSineHSev3Sp2Train.arff) -e (SimpleClassificationPerformanceEvaluator -r 1000) -f 10 -i -1 -d data/ArtificialDataSets/sineH/dataSineHSev3Sp2Train/dataSineHSev3Sp2Train$i.dump -o data/ArtificialDataSets/sineH/dataSineHSev3Sp2Train/dataSineHSev3Sp2Train$i.out"
    java -cp target/DDD-0.0.1-SNAPSHOT.jar moa.DoTask "EvaluatePrequential -l (meta.DDD -r ${prime[i-1]} -w 1 -l 1 -h 0.05 -e (meta.OnlineBagging -l trees.HoeffdingTree -d 0.05) -d (EarlyDriftDetectionMethod -w 0.95 -d 0.95)) -s (ArffFileStream -f data/ArtificialDataSets/sineH/dataSineHSev3Sp3Train.arff) -e (SimpleClassificationPerformanceEvaluator -r 1000) -f 10 -i -1 -d data/ArtificialDataSets/sineH/dataSineHSev3Sp3Train/dataSineHSev3Sp3Train$i.dump -o data/ArtificialDataSets/sineH/dataSineHSev3Sp3Train/dataSineHSev3Sp3Train$i.out"
done
