#!/bin/bash
prime=(2 3 5 7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89 97 101 103 107 109 113)
for i in `seq 1 30`;
do
    java -cp target/DDD-0.0.1-SNAPSHOT.jar moa.DoTask "EvaluatePrequential -l (meta.DDD -r ${prime[i-1]} -w 1 -l 1 -h 0.005 -e (meta.OnlineBagging -l trees.HoeffdingTree -d 0.005) -d (EarlyDriftDetectionMethod -w 0.95 -d 0.95)) -s (ArffFileStream -f data/ArtificialDataSets/sine/dataSineSev1Sp1Test.arff) -e (SimpleClassificationPerformanceEvaluator -r 250) -f 25 -i -1 -d data/ArtificialDataSets/sine/dataSineSev1Sp1Test/dataSineSev1Sp1Test$i.dump -o data/ArtificialDataSets/sine/dataSineSev1Sp1Test/dataSineSev1Sp1Test$i.out"
    java -cp target/DDD-0.0.1-SNAPSHOT.jar moa.DoTask "EvaluatePrequential -l (meta.DDD -r ${prime[i-1]} -w 1 -l 1 -h 0.005 -e (meta.OnlineBagging -l trees.HoeffdingTree -d 0.005) -d (EarlyDriftDetectionMethod -w 0.95 -d 0.95)) -s (ArffFileStream -f data/ArtificialDataSets/sine/dataSineSev1Sp1Train.arff) -e (SimpleClassificationPerformanceEvaluator -r 1000) -f 25 -i -1 -d data/ArtificialDataSets/sine/dataSineSev1Sp1Train/dataSineSev1Sp1Train$i.dump -o data/ArtificialDataSets/sine/dataSineSev1Sp1Train/dataSineSev1Sp1Train$i.out"
    java -cp target/DDD-0.0.1-SNAPSHOT.jar moa.DoTask "EvaluatePrequential -l (meta.DDD -r ${prime[i-1]} -w 1 -l 1 -h 0.005 -e (meta.OnlineBagging -l trees.HoeffdingTree -d 0.005) -d (EarlyDriftDetectionMethod -w 0.95 -d 0.95)) -s (ArffFileStream -f data/ArtificialDataSets/sine/dataSineSev1Sp2Train.arff) -e (SimpleClassificationPerformanceEvaluator -r 1000) -f 25 -i -1 -d data/ArtificialDataSets/sine/dataSineSev1Sp2Train/dataSineSev1Sp2Train$i.dump -o data/ArtificialDataSets/sine/dataSineSev1Sp2Train/dataSineSev1Sp2Train$i.out"
    java -cp target/DDD-0.0.1-SNAPSHOT.jar moa.DoTask "EvaluatePrequential -l (meta.DDD -r ${prime[i-1]} -w 1 -l 1 -h 0.005 -e (meta.OnlineBagging -l trees.HoeffdingTree -d 0.005) -d (EarlyDriftDetectionMethod -w 0.95 -d 0.95)) -s (ArffFileStream -f data/ArtificialDataSets/sine/dataSineSev1Sp3Train.arff) -e (SimpleClassificationPerformanceEvaluator -r 1000) -f 25 -i -1 -d data/ArtificialDataSets/sine/dataSineSev1Sp3Train/dataSineSev1Sp3Train$i.dump -o data/ArtificialDataSets/sine/dataSineSev1Sp3Train/dataSineSev1Sp3Train$i.out"
    java -cp target/DDD-0.0.1-SNAPSHOT.jar moa.DoTask "EvaluatePrequential -l (meta.DDD -r ${prime[i-1]} -w 1 -l 1 -h 0.005 -e (meta.OnlineBagging -l trees.HoeffdingTree -d 0.005) -d (EarlyDriftDetectionMethod -w 0.95 -d 0.95)) -s (ArffFileStream -f data/ArtificialDataSets/sine/dataSineSev2Sp1Test.arff) -e (SimpleClassificationPerformanceEvaluator -r 250) -f 25 -i -1 -d data/ArtificialDataSets/sine/dataSineSev2Sp1Test/dataSineSev2Sp1Test$i.dump -o data/ArtificialDataSets/sine/dataSineSev2Sp1Test/dataSineSev2Sp1Test$i.out"
    java -cp target/DDD-0.0.1-SNAPSHOT.jar moa.DoTask "EvaluatePrequential -l (meta.DDD -r ${prime[i-1]} -w 1 -l 1 -h 0.005 -e (meta.OnlineBagging -l trees.HoeffdingTree -d 0.005) -d (EarlyDriftDetectionMethod -w 0.95 -d 0.95)) -s (ArffFileStream -f data/ArtificialDataSets/sine/dataSineSev2Sp1Train.arff) -e (SimpleClassificationPerformanceEvaluator -r 1000) -f 25 -i -1 -d data/ArtificialDataSets/sine/dataSineSev2Sp1Train/dataSineSev2Sp1Train$i.dump -o data/ArtificialDataSets/sine/dataSineSev2Sp1Train/dataSineSev2Sp1Train$i.out"
    java -cp target/DDD-0.0.1-SNAPSHOT.jar moa.DoTask "EvaluatePrequential -l (meta.DDD -r ${prime[i-1]} -w 1 -l 1 -h 0.005 -e (meta.OnlineBagging -l trees.HoeffdingTree -d 0.005) -d (EarlyDriftDetectionMethod -w 0.95 -d 0.95)) -s (ArffFileStream -f data/ArtificialDataSets/sine/dataSineSev2Sp2Train.arff) -e (SimpleClassificationPerformanceEvaluator -r 1000) -f 25 -i -1 -d data/ArtificialDataSets/sine/dataSineSev2Sp2Train/dataSineSev2Sp2Train$i.dump -o data/ArtificialDataSets/sine/dataSineSev2Sp2Train/dataSineSev2Sp2Train$i.out"
    java -cp target/DDD-0.0.1-SNAPSHOT.jar moa.DoTask "EvaluatePrequential -l (meta.DDD -r ${prime[i-1]} -w 1 -l 1 -h 0.005 -e (meta.OnlineBagging -l trees.HoeffdingTree -d 0.005) -d (EarlyDriftDetectionMethod -w 0.95 -d 0.95)) -s (ArffFileStream -f data/ArtificialDataSets/sine/dataSineSev2Sp3Train.arff) -e (SimpleClassificationPerformanceEvaluator -r 1000) -f 25 -i -1 -d data/ArtificialDataSets/sine/dataSineSev2Sp3Train/dataSineSev2Sp3Train$i.dump -o data/ArtificialDataSets/sine/dataSineSev2Sp3Train/dataSineSev2Sp3Train$i.out"
    java -cp target/DDD-0.0.1-SNAPSHOT.jar moa.DoTask "EvaluatePrequential -l (meta.DDD -r ${prime[i-1]} -w 1 -l 1 -h 0.005 -e (meta.OnlineBagging -l trees.HoeffdingTree -d 0.005) -d (EarlyDriftDetectionMethod -w 0.95 -d 0.95)) -s (ArffFileStream -f data/ArtificialDataSets/sine/dataSineSev3Sp1Test.arff) -e (SimpleClassificationPerformanceEvaluator -r 250) -f 25 -i -1 -d data/ArtificialDataSets/sine/dataSineSev3Sp1Test/dataSineSev3Sp1Test$i.dump -o data/ArtificialDataSets/sine/dataSineSev3Sp1Test/dataSineSev3Sp1Test$i.out"
    java -cp target/DDD-0.0.1-SNAPSHOT.jar moa.DoTask "EvaluatePrequential -l (meta.DDD -r ${prime[i-1]} -w 1 -l 1 -h 0.005 -e (meta.OnlineBagging -l trees.HoeffdingTree -d 0.005) -d (EarlyDriftDetectionMethod -w 0.95 -d 0.95)) -s (ArffFileStream -f data/ArtificialDataSets/sine/dataSineSev3Sp1Train.arff) -e (SimpleClassificationPerformanceEvaluator -r 1000) -f 25 -i -1 -d data/ArtificialDataSets/sine/dataSineSev3Sp1Train/dataSineSev3Sp1Train$i.dump -o data/ArtificialDataSets/sine/dataSineSev3Sp1Train/dataSineSev3Sp1Train$i.out"
    java -cp target/DDD-0.0.1-SNAPSHOT.jar moa.DoTask "EvaluatePrequential -l (meta.DDD -r ${prime[i-1]} -w 1 -l 1 -h 0.005 -e (meta.OnlineBagging -l trees.HoeffdingTree -d 0.005) -d (EarlyDriftDetectionMethod -w 0.95 -d 0.95)) -s (ArffFileStream -f data/ArtificialDataSets/sine/dataSineSev3Sp2Train.arff) -e (SimpleClassificationPerformanceEvaluator -r 1000) -f 25 -i -1 -d data/ArtificialDataSets/sine/dataSineSev3Sp2Train/dataSineSev3Sp2Train$i.dump -o data/ArtificialDataSets/sine/dataSineSev3Sp2Train/dataSineSev3Sp2Train$i.out"
    java -cp target/DDD-0.0.1-SNAPSHOT.jar moa.DoTask "EvaluatePrequential -l (meta.DDD -r ${prime[i-1]} -w 1 -l 1 -h 0.005 -e (meta.OnlineBagging -l trees.HoeffdingTree -d 0.005) -d (EarlyDriftDetectionMethod -w 0.95 -d 0.95)) -s (ArffFileStream -f data/ArtificialDataSets/sine/dataSineSev3Sp3Train.arff) -e (SimpleClassificationPerformanceEvaluator -r 1000) -f 25 -i -1 -d data/ArtificialDataSets/sine/dataSineSev3Sp3Train/dataSineSev3Sp3Train$i.dump -o data/ArtificialDataSets/sine/dataSineSev3Sp3Train/dataSineSev3Sp3Train$i.out"
done